# Generated by Django 2.2.8 on 2022-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
